title: ROOCS
logo: /assets/roocs-logo.png
author: Copyright Â© 2021 Project Roocs
email: ag.stephens@stfc.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  roocs - remote operations on climate simulations

github_username:  roocs
# Build settings
theme: jekyll-theme-cayman

header_pages:
  - about.md
  - overview.md
  - contact.md
