title: net-zero-dri
logo: /images/netzero_logo_dark.png
author: Copyright Â© 2021 Project
email: support@ceda.ac.uk 
description: >- # this means to ignore newlines until "baseurl:"
  net-zero-dri - Net Zero Digital Research Infrastructure

github_username:  net-zero-dri
# Build settings
theme: minima
google_tag_manager: true
gtm_container: GTM-NDG2XX7

header_pages:
  - about.md
  - overview.md
  - contact.md
